import os

from dotenv import load_dotenv

load_dotenv()
class Config:
    def __init__(self):
        self.DEBUG = False
        self.SECRET_KEY = os.getenv("2ddccb2ecf5dd8d76e1d9e24930c10f4528122ed3915c9acc42ec734c0b743e0", "no flask secret key") # generated by secrets.token_hex()

class DevConfig(Config):
    def __init__(self):
        super().__init__()
        self.DEBUG = True
        
        self.CACHE_TYPE = "SimpleCache"
        self.CACHE_DEFAULT_TIMEOUT = 3000

        self.SESSION_TYPE = "redis"
        self.SESSION_COOKIE_HTTPONLY = True
        self.SESSION_COOKIE_SAMESITE = "None"
        self.SESSION_COOKIE_NAME = "fb_session"
        self.SESSION_COOKIE_SECURE = False